# Site settings
title: Ernest
email: earneyzxl@gmail.com
description: > # this means to ignore newlines until "baseurl:"
baseurl: "" # the subpath of your site, e.g. /blog/

url: "http://earne.github.io" # the base hostname & protocol for your site
twitter_username: earneyzxl
github_username:  earne

disqus: earne
analytics: UA-60719663-1

#nav config
nav:
    - text: Home
      url: /index.html
    - text: About
      url: /about/
